openapi: 3.0.0
info:
  title: Sample API
  description: Sample API
  version: 1.0.0
paths: {}
components:
  schemas:
    BalanceSnapshot:
      title: Balance Snapshot
      description: Running snapshots of total balances
      type: object
      required:
        - id
        - symbol
      properties:
        id:
          type: integer
          format: int64
          description: Identifier
        quantity:
          type: integer
          format: int64
          description: Asset quantity
        symbol:
          type: string
          description: Asset symbol
